version: '{build}'
clone_depth: 1

image:
#- Ubuntu
- Visual Studio 2017

environment:
  ApiKey:
    secure: SeomICfFXAQobyK5uMGeAhb0uljBxicG4Z56pWxWCXA=

branches:
  only:
  - master
  - dev

configuration:
  - Release

init:
  - ps: git config --global core.autocrlf true

before_build:
- ps: dotnet --info
- ps: "Get-ChildItem Env:"

build_script:
- ps: dotnet build ./src/FluentModbus/FluentModbus.csproj -c $Env:CONFIGURATION /p:Build=$Env:APPVEYOR_BUILD_NUMBER /p:IsFinalBuild=$Env:APPVEYOR_REPO_TAG

test_script:
- ps: dotnet test ./tests/FluentModbus.Tests -c $Env:CONFIGURATION /p:BuildProjectReferences=false

artifacts:
  - path: ./artifacts/packages/**/*.nupkg

deploy:

# MyGet (dev)
  - provider: NuGet
    server: https://www.myget.org/F/apollo3zehn-dev/api/v2/package
    api_key:
      secure: DVadlPknnKPMR4F2+3VqeU7BFFmtLcXDHzkySA590MqQNIdzbx8HRuaPwDVbHRqX
    skip_symbols: true
    artifact: /.*\.nupkg/ 
    on:
      branch: dev
      CI_WINDOWS: true

# NuGet (master)
  - provider: NuGet
    server: https://www.nuget.org/api/v2/package
    api_key:
      secure: WqZcnRwOmzIa+INti/HnihBrUz0u71rTRNElX/2wbuAIbzMX6SV8h4OxJtCaX2vN
    skip_symbols: true
    artifact: /.*\.nupkg/ 
    on:
      CI_WINDOWS: true
      APPVEYOR_REPO_TAG: true